
#ifndef DISPLAY_H
#define DISPLAY_H
#include "Hardward.h"
#include <ATCommand.h>

#define INDEX_RTC       0
#define INDEX_ACCEL     1
#define INDEX_GYRO      2
#define INDEX_COMPASS   3
#define INDEX_EULER     4


#define  LCD_SIZE_W 160
#define  LCD_SIZE_H 80

#define  ICON_STATUA_GAP_X    2 
#define  ICON_STATUA_GAP_Y    0 

#define  ICON_CHARGE_SIZE_W        16
#define  ICON_CHARGE_SIZE_H        16

#define  ICON_BAT_SIZE_W        28
#define  ICON_BAT_SIZE_H        16

#define  ICON_BLESTATU_SIZE_W        16
#define  ICON_BLESTATU_SIZE_H        16

#define  ICON_WIFISTATU_SIZE_W        16
#define  ICON_WIFISTATU_SIZE_H        16

#define  ICON_CALENDAR_SIZE_W        20
#define  ICON_CALENDAR_SIZE_H        20

#define  ICON_TAB_SIZE_W        160
#define  ICON_TAB_SIZE_H        60

#define  ICON_HR_SIZE_W        55
#define  ICON_HR_SIZE_H        55

#define  ICON_SETTING_SIZE_W        60
#define  ICON_SETTING_SIZE_H        60

#define  ICON_BLE_SIZE_W        69
#define  ICON_BLE_SIZE_H        69

#define  ICON_SETTING_BLE_SWITCH_SIZE_W        50
#define  ICON_SETTING_BLE_SWITCH_SIZE_H        20

#define  ICON_SENSOR_SIZE_W        55
#define  ICON_SENSOR_SIZE_H        55

#define  ICON_WIFI_SIZE_W        60
#define  ICON_WIFI_SIZE_H        60

#define  ICON_SETTING_WIFI_SWITCH_SIZE_W        50
#define  ICON_SETTING_WIFI_SWITCH_SIZE_H        20

#define  ICON_DISPLAY_SIZE_W        59
#define  ICON_DISPLAY_SIZE_H        59

#define  ICON_CHARGE_LOCATION_X    (LCD_SIZE_W - ICON_CHARGE_SIZE_W - ICON_STATUA_GAP_X)
#define  ICON_CHARGE_LOCATION_Y    (LCD_SIZE_H - ICON_CHARGE_SIZE_H - ICON_STATUA_GAP_Y)

#define  ICON_BAT_LOCATION_X    (ICON_CHARGE_LOCATION_X - ICON_BAT_SIZE_W - ICON_STATUA_GAP_X)
#define  ICON_BAT_LOCATION_Y    (LCD_SIZE_H - ICON_BAT_SIZE_H - ICON_STATUA_GAP_Y)

#define  ICON_BLESTATU_LOCATION_X    (ICON_BAT_LOCATION_X - ICON_BLESTATU_SIZE_W - ICON_STATUA_GAP_X)
#define  ICON_BLESTATU_LOCATION_Y    (LCD_SIZE_H - ICON_BLESTATU_SIZE_H - ICON_STATUA_GAP_Y)

#define  ICON_WIFISTATU_LOCATION_X    (ICON_BLESTATU_LOCATION_X - ICON_WIFISTATU_SIZE_W - ICON_STATUA_GAP_X)
#define  ICON_WIFISTATU_LOCATION_Y    (LCD_SIZE_H - ICON_WIFISTATU_SIZE_H - ICON_STATUA_GAP_Y)

#define  ICON_CALENDAR_LOCATION_X    1
#define  ICON_CALENDAR_LOCATION_Y    (LCD_SIZE_H - ICON_CALENDAR_SIZE_H )

#define  STR_BAT_LOCATION_X    (ICON_BAT_LOCATION_X + 1)
#define  STR_BAT_LOCATION_Y    (ICON_BAT_LOCATION_Y + 4)

#define  STR_DATE_LOCATION_X    1
#define  STR_DATE_LOCATION_Y    (LCD_SIZE_H - 13)

#define  STR_TIME_LOCATION_X    3
#define  STR_TIME_LOCATION_Y    15

#define  STR_TIME_STATUS_LOCATION_X    15
#define  STR_TIME_STATUS_LOCATION_Y    (LCD_SIZE_H - 16)

#define  STR_ACC_GAP_X 53
#define  STR_ACC_GAP_Y 16 
#define  STR_ACC_X_LOCATION_X  53
#define  STR_ACC_X_LOCATION_Y  18
#define  STR_ACC_Y_LOCATION_X  STR_ACC_X_LOCATION_X
#define  STR_ACC_Y_LOCATION_Y  (STR_ACC_X_LOCATION_Y + STR_ACC_GAP_Y)
#define  STR_ACC_Z_LOCATION_X  STR_ACC_X_LOCATION_X
#define  STR_ACC_Z_LOCATION_Y  (STR_ACC_Y_LOCATION_Y + STR_ACC_GAP_Y)

#define  STR_GYR_X_LOCATION_X  (STR_ACC_X_LOCATION_X + STR_ACC_GAP_X )
#define  STR_GYR_X_LOCATION_Y  (STR_ACC_X_LOCATION_Y)
#define  STR_GYR_Y_LOCATION_X  (STR_ACC_X_LOCATION_X + STR_ACC_GAP_X )
#define  STR_GYR_Y_LOCATION_Y  (STR_ACC_X_LOCATION_Y + STR_ACC_GAP_Y)
#define  STR_GYR_Z_LOCATION_X  (STR_ACC_X_LOCATION_X + STR_ACC_GAP_X )
#define  STR_GYR_Z_LOCATION_Y  (STR_ACC_Y_LOCATION_Y + STR_ACC_GAP_Y)

#define  STR_MAG_X_LOCATION_X  (STR_GYR_X_LOCATION_X + STR_ACC_GAP_X)
#define  STR_MAG_X_LOCATION_Y  (STR_ACC_X_LOCATION_Y)
#define  STR_MAG_Y_LOCATION_X  (STR_GYR_X_LOCATION_X + STR_ACC_GAP_X)
#define  STR_MAG_Y_LOCATION_Y  (STR_ACC_X_LOCATION_Y + STR_ACC_GAP_Y)
#define  STR_MAG_Z_LOCATION_X  (STR_GYR_X_LOCATION_X + STR_ACC_GAP_X)
#define  STR_MAG_Z_LOCATION_Y  (STR_ACC_Y_LOCATION_Y + STR_ACC_GAP_Y)


#define  ICON_HR_LOCATION_X        5
#define  ICON_HR_LOCATION_Y        2

#define  ICON_TAB_LOCATION_X        0
#define  ICON_TAB_LOCATION_Y        0

#define  ICON_SETTING_LOCATION_X        5
#define  ICON_SETTING_LOCATION_Y        2

#define  ICON_BLE_LOCATION_X        5
#define  ICON_BLE_LOCATION_Y        2

#define  ICON_WIFI_LOCATION_X        5
#define  ICON_WIFI_LOCATION_Y        2

#define  ICON_SENSOR_LOCATION_X        5
#define  ICON_SENSOR_LOCATION_Y        2

#define  ICON_DISPLAY_LOCATION_X        5
#define  ICON_DISPLAY_LOCATION_Y        2

#define  FONT_RTC_SIZE 7   
#define  FONT_RTC_STATUS_SIZE 2   

#define  FONT_HR_SIZE 7

#define  STR_HR_LOCATION_X    158
#define  STR_HR_LOCATION_Y    2

#define  FONT_SETTING_SIZE 4
#define  STR_SETTING_LOCATION_X    75
#define  STR_SETTING_LOCATION_Y    20

#define  FONT_SETTING_MEMO_SIZE 1
#define  STR_SETTING_MEMO_LOCATION_X    20
#define  STR_SETTING_MEMO_LOCATION_Y    70

#define  FONT_SETTING_WIFI_SIZE 2
#define  STR_SETTING_WIFI_LOCATION_X    65
#define  STR_SETTING_WIFI_LOCATION_Y    0

#define  FONT_SETTING_WIFI_MEMO_SIZE 1
#define  STR_SETTING_WIFI_MEMO_LOCATION_X    20
#define  STR_SETTING_WIFI_MEMO_LOCATION_Y    70

#define  ICON_SETTING_WIFI_SWITCH_LOCATION_X    80
#define  ICON_SETTING_WIFI_SWITCH_LOCATION_Y    45

#define  FONT_SETTING_BLE_SIZE 2
#define  STR_SETTING_BLE_LOCATION_X    STR_SETTING_WIFI_LOCATION_X
#define  STR_SETTING_BLE_LOCATION_Y    STR_SETTING_WIFI_LOCATION_Y

#define  FONT_SETTING_BLE_MEMO_SIZE 1
#define  STR_SETTING_BLE_MEMO_LOCATION_X    STR_SETTING_WIFI_MEMO_LOCATION_X
#define  STR_SETTING_BLE_MEMO_LOCATION_Y    STR_SETTING_WIFI_MEMO_LOCATION_Y

#define  ICON_SETTING_BLE_SWITCH_LOCATION_X    80
#define  ICON_SETTING_BLE_SWITCH_LOCATION_Y    45

#define  FONT_SETTING_DISPLAY_SIZE 2
#define  STR_SETTING_DISPLAY_LOCATION_X    STR_SETTING_WIFI_LOCATION_X
#define  STR_SETTING_DISPLAY_LOCATION_Y    STR_SETTING_WIFI_LOCATION_Y

#define  FONT_SETTING_DISPLAY_MEMO_SIZE 1
#define  STR_SETTING_DISPLAY_MEMO_LOCATION_X    STR_SETTING_WIFI_MEMO_LOCATION_X
#define  STR_SETTING_DISPLAY_MEMO_LOCATION_Y    STR_SETTING_WIFI_MEMO_LOCATION_Y

#define  FONT_SETTING_DISPLAY_LIGHT_SIZE 4
#define  STR_SETTING_DISPLAY_LIGHT_LOCATION_X    155
#define  STR_SETTING_DISPLAY_LIGHT_LOCATION_Y    20

#define  FONT_SETTING_SENSOR_SIZE 2
#define  STR_SETTING_SENSOR_LOCATION_X    STR_SETTING_WIFI_LOCATION_X
#define  STR_SETTING_SENSOR_LOCATION_Y    STR_SETTING_WIFI_LOCATION_Y

#define  FONT_SETTING_SENSOR_MEMO_SIZE 1
#define  STR_SETTING_SENSOR_MEMO_LOCATION_X    STR_SETTING_WIFI_MEMO_LOCATION_X
#define  STR_SETTING_SENSOR_MEMO_LOCATION_Y    STR_SETTING_WIFI_MEMO_LOCATION_Y



void Display_Setup();
void Display_ON();
void Display_OFF(); 

void Display_RTC();
void Display_Battery(String percent) ;
void Display_ChargeStatus(bool status);
void Display_BLE_Name(String ble_name);
void Display_BLEStatu(uint8_t status);
void Display_WiFiStatu(uint8_t status);
void Display_WiFi_Switch(uint8_t status);
void Display_HR(uint8_t heart);
void Display_Sensor(IMU_DATA imu,uint8_t Index);
void Display_BLE_ATCommand(String display);
uint8_t Display_ATCommand_Process(uint8_t Index);
void Display_IMU_Switch(bool status);
void Display_initial_refresh();
#endif